version: 2.1

jobs:
  runner-test:
    machine: true
    resource_class: fortefrankie/macosselfhosted
    steps:
      - run: echo "Hi I'm on Ruers!"   
   build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.17.1
    macos:
      xcode: "14.2.0"
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Javascript IIFE test
          command: npm test
      - store_artifacts:
          path: ~/iife-javascript-1
